version: 2
jobs:
  testMain:
    steps:
      - run: # run tests
        name: test
        command: npm run test

      - run:
        name: coverage
        command: |
          npm run coverage

  testStaking:
    steps:
      - run: # run tests
        name: test staking model
        command: |
          cd stakingModel
          npm ci
          npm run test 
          cd ..

      - run:
        name: coverage
        command: |
          npm run coverage

  coverage:
    steps:
      - run:
        name: report coverage
        command: npm run coverage:report

  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"

      - run:
          command: "sudo npm install -g ts-node"

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install-npm
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - testMain:
          requires:
            - build
      - testStaking:
          requires:
            - build
      - coverage:
          requires:
            - testMain
            - testStaking
